# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f014d6e8329106df39ed4778f4ae085c3499252ac9e65d26d297c73ed7688e2c6e78a182778dafe02cd73364f2fd89e9c11b15627809c5cb666e7454c58c707

test:
  secret_key_base: bdc562347657f419e6640ce30bdd67cca9038e7b182e8a0b45486a4f9e0db4af81852cde8808abf07137f7fe05dd9fc2c24724e8e9fb36583150107be9513c4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
